//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CivilEmail.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamanlayici
    {
        public int id { get; set; }
        public string ZamanAdi { get; set; }
        public string ZamanTuru { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string YinelenenTur { get; set; }
        public Nullable<bool> CalismaTipi { get; set; }
        public Nullable<int> Gunluk { get; set; }
        public Nullable<int> Haftalik { get; set; }
        public Nullable<int> Aylik { get; set; }
        public Nullable<int> AyGunu { get; set; }
        public string AyTuru { get; set; }
        public Nullable<System.TimeSpan> CalismaBaslangic { get; set; }
        public Nullable<System.TimeSpan> CalismaBiris { get; set; }
        public Nullable<System.DateTime> ZamanBaslangic { get; set; }
        public Nullable<System.DateTime> ZamanBitis { get; set; }
        public string ZamanTipi { get; set; }
        public string Gunler { get; set; }
        public Nullable<int> CalismaSuresi { get; set; }
    }
}
